// =====================================================
// PAYSLIPS PAGE - Simple and Easy to Understand
// =====================================================

// Import React hooks for managing state and side effects
import { useState, useEffect } from "react";

// Import navigation and API
import { Link, useNavigate } from "react-router-dom";
import API from "../services/api";

// List of month names
const monthsList = [
    "", "January", "February", "March", "April", "May", "June", 
    "July", "August", "September", "October", "November", "December"
];

// =====================================================
// COMPONENT: Payslips Page
// =====================================================
function Payslips() {
    // ------------------------------------------
    // STEP 1: Define state variables
    // ------------------------------------------
    
    // payslips - array to store list of payslips
    const [payslips, setPayslips] = useState([]);
    
    // loading - shows if data is being loaded
    const [loading, setLoading] = useState(true);
    
    // user - stores the logged in user's information
    const [user, setUser] = useState(null);
    
    // navigate - used to redirect to other pages
    const navigate = useNavigate();

    // ------------------------------------------
    // STEP 2: Run when component loads
    // ------------------------------------------
    useEffect(function() {
        // Check if user is logged in
        const token = localStorage.getItem("token");
        const userData = localStorage.getItem("user");
        
        if (!token) {
            // No token - redirect to login
            navigate("/");
        } 
        else {
            // Get user data
            const parsedUser = userData ? JSON.parse(userData) : null;
            setUser(parsedUser);
            
            // Fetch payslips
            fetchPayslips(parsedUser);
        }
    }, [navigate]);

    // ------------------------------------------
    // STEP 3: Fetch payslips from server
    // ------------------------------------------
    const fetchPayslips = async function(currentUser) {
        try {
            // If admin, get all payslips
            if (currentUser && currentUser.role === "admin") {
                const response = await API.get("/payslips");
                setPayslips(response.data);
            } 
            // If employee, get only their payslips
            else {
                const response = await API.get("/payslips/my");
                setPayslips(response.data);
            }
        } 
        catch (err) {
            // Log error but continue (shows empty state)
            console.error("Error fetching payslips:", err);
        }
        finally {
            setLoading(false);
        }
    };

    // ------------------------------------------
    // STEP 4: Get month name from value
    // ------------------------------------------
    const getMonthName = function(monthValue) {
        // Convert month value to number and get name from array
        return monthsList[parseInt(monthValue)] || monthValue;
    };

    // ------------------------------------------
    // STEP 5: Format currency
    // ------------------------------------------
    const formatCurrency = function(amount) {
        // Format number as USD currency
        return "$" + Number(amount).toLocaleString();
    };

    // ------------------------------------------
    // STEP 6: Render the page
    // ------------------------------------------
    return (
        <div className="page-container">
            
            {/* Header */}
            <div className="page-header">
                <div>
                    <Link to="/dashboard" className="back-link">Back</Link>
                    <h1 className="page-title">
                        {user?.role === "admin" ? "All Payslips" : "My Payslips"}
                    </h1>
                </div>
                
                {/* Show user info */}
                {user && (
                    <div>
                        <span>{user.name}</span>
                        <span className={"badge " + (user.role === "admin" ? "badge-admin" : "badge-employee")} style={{marginLeft: "10px"}}>
                            {user.role}
                        </span>
                    </div>
                )}
            </div>

            {/* Loading State */}
            {loading ? (
                <p>Loading...</p>
            ) : 
            
            // If no payslips, show empty state
            payslips.length === 0 ? (
                <div className="card">
                    <h4>No Payslip Records Found</h4>
                    <p>
                        {user?.role === "admin" 
                            ? "No payroll has been generated yet. Go to Payroll to generate payslips."
                            : "Your payslips will appear here once payroll is generated by your administrator."
                        }
                    </p>
                    <Link to={user?.role === "admin" ? "/payroll" : "/dashboard"} className="btn btn-primary" style={{marginTop: "10px"}}>
                        {user?.role === "admin" ? "Go to Payroll" : "Back to Dashboard"}
                    </Link>
                </div>
            ) : (
                
            // Show payslip list
            <div>
                <p style={{marginBottom: "15px"}}>
                    <strong>{payslips.length}</strong> {payslips.length === 1 ? "Payslip" : "Payslips"} found
                </p>
                
                {/* Display each payslip as a card */}
                {payslips.map(function(payslip) {
                    return (
                        <div key={payslip._id} className="card" style={{marginBottom: "15px"}}>
                            <h4>{getMonthName(payslip.month)} {payslip.year}</h4>
                            
                            <div style={{marginTop: "10px"}}>
                                <p><strong>Employee:</strong> {payslip.employeeId?.name || "Unknown"}</p>
                                <p><strong>Email:</strong> {payslip.employeeId?.email || "N/A"}</p>
                                <hr />
                                <p><strong>Basic Salary:</strong> {formatCurrency(payslip.salary)}</p>
                                <p style={{color: "red"}}><strong>Deductions:</strong> -{formatCurrency(payslip.deductions || 0)}</p>
                                <p style={{color: "green"}}><strong>Bonuses:</strong> +{formatCurrency(payslip.bonuses || 0)}</p>
                                <hr />
                                <p style={{fontSize: "18px", fontWeight: "bold"}}>
                                    <strong>Net Salary:</strong> {formatCurrency(payslip.netSalary)}
                                </p>
                            </div>
                        </div>
                    );
                })}
            </div>
            )}
        </div>
    );
}

// Export this component to be used in other files
export default Payslips;
